version: '3.8'

services:
  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ./nginx/:/etc/nginx/conf.d
    restart: always

  json-server:
    image: vimagick/json-server
    command: -h 0.0.0.0 -p 8000 -w db.json
    ports:
      - "8000:8000"
    volumes:
      - ./data:/data
    restart: always
